name: FastUI
schemes:
  FastUI8:
    build:
      targets:
        FastUI8: build
  FastUI13:
    build:
      targets:
        FastUI13: build
targets:
  FastUI8:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: plists/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 8.0
      PRODUCT_BUNDLE_IDENTIFIER: com.muiz.idn.$(TARGET_NAME)
    sources:
      - path: Sources/FastUI8
        includes: 
          - "*.{swift}"
    dependencies:
      - carthage: FlexLayout
  FastUI13:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: plists/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      PRODUCT_BUNDLE_IDENTIFIER: com.muiz.idn.$(TARGET_NAME)
    sources:
      - path: Sources/FastUI13
        includes: 
          - "*.{swift}"
  FastUIApp:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: App/FastUIApp/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 8.0
      PRODUCT_BUNDLE_IDENTIFIER: com.muiz.idn.$(TARGET_NAME)
    sources: App/FastUIApp
    dependencies:
      - target: FastUI8
  SwiftUIApp:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: App/SwiftUIApp/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      PRODUCT_BUNDLE_IDENTIFIER: com.muiz.idn.$(TARGET_NAME)
    sources: App/SwiftUIApp
    dependencies:
      - target: FastUI13
