name: FastUI
schemes:
  FastUI:
    build:
      targets:
        FastUI: build
  FastUIApp:
    build:
      targets:
        FastUIApp: run
targets:
  FastUI:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: plists/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 8.0
      PRODUCT_BUNDLE_IDENTIFIER: com.muiz.idn.$(TARGET_NAME)
    sources:
      - path: Sources/FastUI
        includes: 
          - "*.{swift}"
    dependencies:
      - carthage: FlexLayout
  FastUIApp:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: App/FastUIApp/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 8.0
      PRODUCT_BUNDLE_IDENTIFIER: com.muiz.idn.$(TARGET_NAME)
    sources: App/FastUIApp
    dependencies:
      - target: FastUI
  SwiftUIApp:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: App/SwiftUIApp/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      PRODUCT_BUNDLE_IDENTIFIER: com.muiz.idn.$(TARGET_NAME)
    sources: App/SwiftUIApp
